MobilityProd/Online.Registration.Web/Areas/Admin/Controllers/UserGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SNT.Utility;
using Telerik.Web.Mvc;
using System.Web.Routing;
using Online.Registration.Web.Helper;
using Online.Registration.DAL.Models;
using Online.Registration.Web.ViewModels;
using Online.Registration.Admin.Models;
using Online.Registration.Web.UserSvc;

namespace Online.Registration.Web.Areas.Admin.Controllers
{
    [CustomErrorHandlerAttr(View = "GenericError")]
    public class UserGroupController : Controller
    {
        UserServiceProxy proxy = new UserServiceProxy();
        public RedirectToRouteResult RedirectToException(Exception ex)
        {
            Util.SetSessionErrMsg(ex);
            return RedirectToAction("Error", "AdminHome", new { errCode = "xxx", type = "Admin" });
        }
        public ActionResult Index()
        {
            return GetUserGroupResult(new UserGroup() { Code = string.Empty, Name = string.Empty}, null, false);
        }
        [HttpPost]
        public ActionResult Index(SearchViewModelUserGroup svUserGroup)
        {
            try
            {
                return GetUserGroupResult(svUserGroup, true);
            }
            catch (Exception ex)
            {
                return RedirectToException(ex);
            }
        }
        private ViewResult GetUserGroupResult(SearchViewModelUserGroup svUserGroup, bool isSearch)
        {
            var sUserGroup = new UserGroup()
            {
                Code = svUserGroup.SearchCriterias.Code,
                Name = svUserGroup.SearchCriterias.Name
            };

            svUserGroup.SearchResults = GetUserGroups(sUserGroup, isSearch);
            return View(svUserGroup);
        }
        private ViewResult GetUserGroupResult(UserGroup userGroup, bool? Active, bool isSearch)
        {
            SearchViewModelUserGroup viewUserGroups = new SearchViewModelUserGroup()
            {
                SearchResults = GetUserGroups(userGroup, isSearch, Active)
            };

            return View(viewUserGroups);
        }
        private IEnumerable<UserGroupSearchResults> GetUserGroups(UserGroup userGroup, bool isSearch, bool? active = null)
        {
            int pageSize = Properties.Settings.Default.PageSize;

            UserGroupFind userGroupFind = new UserGroupFind()
            {
                UserGroup = userGroup,
                Active = active,
                PageSize = isSearch ? 0 : pageSize
            };

            var IDs = proxy.UserGroupFind(userGroupFind);
            var userGroups = proxy.UserGroupGet(IDs);

            var results = userGroups.OrderByDescending(a => a.ID).Select(a => new UserGroupSearchResults()
            {
                UserGroupID = a.ID,
                Name = a.Name,
                Code = a.Code,
                Org = a.OrgID != 0 ? Util.GetNameByID(RefType.Organization, a.OrgID).DisplayValue() : "N/A",
                ActiveCheckBox = Util.GetCheckBox(a.Active),
                CreateDT = Util.FormatDateTime(a.CreateDT),
                LastUpdateDT = Util.FormatDateTime(a.LastUpdateDT),
                LastAccessID = a.LastAccessID
            });

            return results;
        }
        public ActionResult Create()
        {
            return View(new UserGroup());
        }
        [HttpPost]
        public ActionResult Create(UserGroup addUserGroup, FormCollection collection)
        {
            try
            {
                string submit = collection["submit"].ToString2();

                if (submit == "Save")
                {
                    // Check for duplicate
                    var userGroup = proxy.UserGroupGet(proxy.UserGroupFind(new UserGroupFind()
                    {
                        UserGroup = new UserGroup() { Code = addUserGroup.Code },
                        Active = true
                    }));

                    if (userGroup.Count() > 0)
                    {
                        ModelState.AddModelError(string.Empty, "User Group Code already exists.");
                        return View();
                    }

                    // Add user Group
                    addUserGroup.CreateDT = DateTime.Now;
                    addUserGroup.LastAccessID = Util.SessionAccess == null ? "System" : Util.SessionAccess.UserName;
                    addUserGroup.Active = true;

                    UserGroupCreateResp oRp = new UserGroupCreateResp();
                    oRp = proxy.UserGroupCreate(addUserGroup);

                    if (oRp.Code == "-1")
                    {
                        if (oRp.Message.StartsWith("Violation of UNIQUE KEY constraint"))
                        {
                            ModelState.AddModelError(string.Empty, string.Format("User Group Code ({0}) already exist!", addUserGroup.Code));
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "Fail to add new User Group: " + oRp.Message);
                        }
                        return View();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToException(ex);
            }
        }
        public ActionResult Edit(int id)
        {
            var userGroup = proxy.UserGroupGet(new int[] { id }).SingleOrDefault();
            UpdateViewUserGroupModel uvUserGroup = new UpdateViewUserGroupModel() 
            {
                UserGroup = userGroup,
                UserGroupRole = GetUserGroupRole(id),
                UserGroupAccess = GetUserGroupAccess(id)
            };
            return View(uvUserGroup);
        }
        [HttpPost]
        public ActionResult Edit(UpdateViewUserGroupModel editUserGroup, FormCollection collection)
        {
            try
            {
                string submit = collection["submit"].ToString2();
                if (submit == "Save")
                {
                    if (editUserGroup.UserGroup.Active == true)
                    {
                        // check for duplicate
                        
                        var userGroups = proxy.UserGroupGet(proxy.UserGroupFind(new UserGroupFind()
                        {
                            UserGroup = new UserGroup() { Code = editUserGroup.UserGroup.Code },
                            Active = true
                        })).ToList();

                        var resultCode = userGroups.ToList().Select(a => a.ID).SingleOrDefault();

                        if (userGroups.Count() > 0 && resultCode != editUserGroup.UserGroup.ID)
                        {
                            var userGroupData = proxy.UserGroupGet(new int[] { editUserGroup.UserGroup.ID }).SingleOrDefault();
                            UpdateViewUserGroupModel uvUserGroup = new UpdateViewUserGroupModel() 
                            { 
                                UserGroup = userGroupData,
                                UserGroupRole = GetUserGroupRole(editUserGroup.UserGroup.ID),
                                UserGroupAccess = GetUserGroupAccess(editUserGroup.UserGroup.ID)
                            };

                            ModelState.AddModelError(string.Empty, "User Group Code already exists.");
                            return View(uvUserGroup);
                        }
                    }

                    // Update User Group
                    editUserGroup.UserGroup.LastUpdateDT = DateTime.Now;
                    editUserGroup.UserGroup.LastAccessID = Util.SessionAccess == null ? "System" : Util.SessionAccess.UserName;

                    proxy.UserGroupUpdate(editUserGroup.UserGroup);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToException(ex);
            }
        }
        private List<UserGroupAccessSearchResults> GetUserGroupAccess(int id)
        {
            int PageSize = Properties.Settings.Default.PageSize;
            List<UserGroupAccessSearchResults> results = new List<UserGroupAccessSearchResults>();

            UserGrpAccessFind userGrpAccessFind = new UserGrpAccessFind()
            {
                UserGrpAccess = new UserGrpAccess()
                {
                    UserGrpID = id
                },
                PageSize = PageSize
            };

            var userGrpAccessIDs = proxy.UserGroupAccessFind(userGrpAccessFind);
            var userGrpAccesss = proxy.UserGroupAccessGet(userGrpAccessIDs);
            if (userGrpAccesss == null)
                return new List<UserGroupAccessSearchResults>();

            results = userGrpAccesss.OrderByDescending(a => a.ID).Select(a => new UserGroupAccessSearchResults()
            {
                UserGroupAccessID = a.ID,
                Access = a.AccessID != 0 ? Util.GetNameByID(RefType.Access, a.AccessID).DisplayValue() : "N/A",
                ActiveCheckBox = Util.GetCheckBox(a.Active),
                CreateDT = Util.FormatDateTime(a.CreateDT),
                LastUpdateDT = Util.FormatDateTime(a.LastUpdateDT),
                LastAccessID = a.LastAccessID,
                Type = RefType.StatusReason
            }).ToList();

            return results;
        }
        private List<UserGroupRoleSearchResults> GetUserGroupRole(int id)
        {
            int PageSize = Properties.Settings.Default.PageSize;
            List<UserGroupRoleSearchResults> results = new List<UserGroupRoleSearchResults>();

            UserGrpRoleFind userGrpRoleFind = new UserGrpRoleFind()
            {
                UserGrpRole = new UserGrpRole()
                {
                    UserGrpID = id
                },
                PageSize = PageSize
            };

            var userGrpRoleIDs = proxy.UserGroupRoleFind(userGrpRoleFind);

MobilityProd/Online.Registration.Web/Areas/Admin/Views/UserGroup/Create.cshtml
@using SNT.Utility;
@using Online.Registration.Web.Helper;

@model Online.Registration.DAL.Models.UserGroup

@{
    ViewBag.Title = "Add User Group";
}
<div class="header">
    <h2>
        @ViewBag.Title
    </h2>
</div>
<br />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend style="margin-right: 500px">Add:</legend>
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.OrgID)
                </td>
                <td>
                    @(Html.Telerik().DropDownListFor(model => Model.OrgID).BindTo(Util.GetList(RefType.Organization, defaultValue:"")))
                    @Html.ValidationMessageFor(model => model.OrgID)
                </td>
            </tr>
            <tr>
                <td>
                    <div style="width: 100px;">
                        @Html.LabelFor(model => model.Code)</div>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Code, new { @style="width:100px"})
                    @Html.ValidationMessageFor(model => model.Code)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Name)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Name, new { @style = "width:250px" })
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
        </table>
    </fieldset>
    <div style="margin: 10px 0px 0px 20px;">
        <button class="t-button t-button-icon" type="submit" name="submit" value="Save">
            <span class="t-icon t-update"></span>Save</button>
        <button class="t-button t-button-icon cancel" type="submit" value="Cancel" name="submit">
            <span class="t-icon t-cancel"></span>Cancel</button>
    </div>
}

MobilityProd/Online.Registration.Web/Areas/Admin/Views/UserGroup/Edit.cshtml
@using Online.Registration.Admin.Models;
@using Online.Registration.Web.Helper;
@using SNT.Utility;

@model UpdateViewUserGroupModel

@{
    ViewBag.Title = "Edit User Group";
}
<div class="header">
    <h2>
        @ViewBag.Title
    </h2>
</div>
<br />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend style="margin-right: 500px">Edit:</legend>
        @Html.HiddenFor(model => model.UserGroup.ID)
        <table>
            <tr>
                <td>@Html.LabelFor(model => model.UserGroup.ID)</td>
                <td>@Html.DisplayFor(model => model.UserGroup.ID)</td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.OrgID)
                </td>
                <td>
                    @(Html.Telerik().DropDownListFor(model => Model.UserGroup.OrgID).BindTo(Util.GetList(RefType.Organization, defaultValue:"")))
                    @Html.ValidationMessageFor(model => model.UserGroup.OrgID)
                </td>
            </tr>
            <tr>
                <td>
                    <div style="width: 100px">
                        @Html.LabelFor(model => model.UserGroup.Code)
                    </div>
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserGroup.Code, new { @style = "width:100px" })
                    @Html.ValidationMessageFor(model => model.UserGroup.Code)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.Name)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserGroup.Name, new { @style = "width:250px" })
                    @Html.ValidationMessageFor(model => model.UserGroup.Name)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.CreateDT)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserGroup.CreateDT, new { @readonly = true, @disabled = true, @Value = Util.FormatDateTime(Model.UserGroup.CreateDT), @style = "width:250px" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.LastUpdateDT)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserGroup.LastUpdateDT, new { @readonly = true, @disabled = true, @Value = Util.FormatDateTime(Model.UserGroup.LastUpdateDT), @style = "width:250px" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.LastAccessID)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.UserGroup.LastAccessID, new { @readonly = true, @disabled = true, @style="width:250px" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserGroup.Active)
                </td>
                <td>
                    @Html.CheckBoxFor(model => model.UserGroup.Active) 
                    @Html.ValidationMessageFor(model => model.UserGroup.Active)
                </td>
            </tr>
        </table>
    </fieldset>
    <div style="margin: 10px 0px 0px 20px;">
        <button class="t-button t-button-icon" type="submit" name="submit" value="Save">
            <span class="t-icon t-update"></span>Save</button>
        <button class="t-button t-button-icon cancel" type="submit" value="Cancel" name="submit">
            <span class="t-icon t-cancel"></span>Cancel</button>
    </div>
    <br />
    if (Model.UserGroup.Active == true)
    {
        <div class="header">
        <h3>User Group Access List</h3>
        </div>       
        <a class="t-button t-button-icontext" href="@Url.Action("Create", "UserGroupAccess", new { userGroupID = Model.UserGroup.ID, type = RefType.UserGroup })">
        <span class="t-icon t-add"></span>Add New</a>
        <br /><br />
        Html.Telerik().Grid<UserGroupAccessSearchResults>(Model.UserGroupAccess).Name("gvwUserGrpAccess")
            .Sortable()
            .Columns(cols =>
            {
                cols.Command(command => command
                    .Custom("Edit")
                    .Text("Edit")
                    .DataRouteValues(route => route.Add(a => a.UserGroupAccessID).RouteKey("id"))
                    .DataRouteValues(route => route.Add(a => RefType.UserGroup).RouteKey("type"))
                    .SendState(false)
                    .Action("Edit", "UserGroupAccess"))
                    .HtmlAttributes(new { style = "text-align: center" })
                    .Width(90)
                    .Title("Action");
                cols.Bound(m => m.Access).Title("Access");
                cols.Bound(m => m.ActiveCheckBox).Title("Active").Width(8).Encoded(false);
                cols.Bound(m => m.CreateDT).Title("Created On");
                cols.Bound(m => m.LastUpdateDT).Title("Last Updated");
                cols.Bound(m => m.LastAccessID).Title("Last Access");
            })
            .DataBinding(binding => binding.Ajax().OperationMode(GridOperationMode.Client))
            .Pageable(paging => paging.PageSize(Util.GridRowsPerPage))
            .Render();
         
        <br /><br />           
        <div class="header">
        <h3>User Group Role List</h3>
        </div>       
        <a class="t-button t-button-icontext" href="@Url.Action("Create", "UserGroupRole", new { userGroupID = Model.UserGroup.ID, type = RefType.UserGroup })">
        <span class="t-icon t-add"></span>Add New</a>
        <br /><br />
        Html.Telerik().Grid<UserGroupRoleSearchResults>(Model.UserGroupRole).Name("gvwUserGrpRole")
            .Sortable()
            .Columns(cols =>
            {
                cols.Command(command => command
                    .Custom("Edit")
                    .Text("Edit")
                    .DataRouteValues(route => route.Add(a => a.UserGroupRoleID).RouteKey("id"))
                    .DataRouteValues(route => route.Add(a => RefType.UserGroup).RouteKey("type"))
                    .SendState(false)
                    .Action("Edit", "UserGroupRole"))
                    .HtmlAttributes(new { style = "text-align: center" })
                    .Width(90)
                    .Title("Action");
                cols.Bound(m => m.UserRole).Title("User Role");
                cols.Bound(m => m.ActiveCheckBox).Title("Active").Width(8).Encoded(false);
                cols.Bound(m => m.CreateDT).Title("Created On");
                cols.Bound(m => m.LastUpdateDT).Title("Last Updated");
                cols.Bound(m => m.LastAccessID).Title("Last Access");
            })
            .DataBinding(binding => binding.Ajax().OperationMode(GridOperationMode.Client))
            .Pageable(paging => paging.PageSize(Util.GridRowsPerPage))
            .Render();
    }
}

    

MobilityProd/Online.Registration.Web/Areas/Admin/Views/UserGroup/Index.cshtml
@using Online.Registration.Admin.Models;
@using Online.Registration.Web.Helper;
@using Online.Registration.DAL.Models;

@model SearchViewModelUserGroup

@{
    ViewBag.Title = "User Group";
    string strForm = "frmUserGroup";
}
<div class="header">
    <h2>
        @ViewBag.Title
    </h2>
    <a class="t-button t-button-icontext" href="@Url.Action("Create")"><span class="t-icon t-add">
    </span>Add New</a>
</div>
<br />
@using (Html.BeginForm("Index", "UserGroup", FormMethod.Post, new { id = strForm, name = strForm }))
{
    <fieldset runat="server">
        <legend style="margin-right: 500px;">Search:</legend>
        <table>
            <tr>
                <td>
                    <div style="width: 100px">
                        @Html.LabelFor(m => m.SearchCriterias.Name)</div>
                </td>
                <td>
                    @Html.TextBoxFor(m => m.SearchCriterias.Name)
                </td>
            </tr>
            <tr>
                <td>
                    <div style="width: 100px">
                       @Html.LabelFor(m => m.SearchCriterias.Code)</div>
                </td>
                <td>
                    @Html.TextBoxFor(m => m.SearchCriterias.Code)
                </td>
            </tr>
        </table>
    </fieldset>
@*</div>*@
   <div style="margin: 10px 0px 0px 20px;">
        <button class="t-button t-button-icontext" type="submit" value="Search" name="Search">
            <span class="t-icon t-search"></span>Search</button>
            <button class="t-button t-button-icontext" type="button" value="Reset" onclick="Reset();">
            <span class="t-icon t-cancel"></span>Reset
        </button>
   </div>
   <br /> 
    @*if (UserGroup == null || UserGroup.SearchResults == null || UserGroup.SearchResults.Count == 0)
    {
        <p>
            No Record Found!</p>
    }*@
    <text><b>Search Result:</b></text>   
    Html.Telerik().Grid<UserGroupSearchResults>(Model.SearchResults).Name("gvwUserGroup")
        .Sortable()
        .Columns(cols => 
        {
            cols.Command(command => command
                .Custom("Edit")
                .Text("Edit")
                .DataRouteValues(route => route.Add(a => a.UserGroupID).RouteKey("id"))
                .SendState(false)
                .Action("Edit", "UserGroup"))
                .HtmlAttributes(new { style = "text-align: center" })
                .Width(90)          
                .Title("Action");
                cols.Bound(m => m.Code).Title("Code").Width(10);
                cols.Bound(m => m.Name).Title("Name").Width(200);
                //cols.Bound(m => m.Org).Title("Organization");
                cols.Bound(m => m.ActiveCheckBox).Title("Active").Width(10).Encoded(false);
                cols.Bound(m => m.CreateDT).Title("Created On");
                cols.Bound(m => m.LastUpdateDT).Title("Last Updated");
                cols.Bound(m => m.LastAccessID).Title("Last Access");
            })
            .DataBinding(binding => binding.Ajax().OperationMode(GridOperationMode.Client))
            .Pageable(paging => paging.PageSize(Util.GridRowsPerPage))
            .Render();
            <br />
}
@section scripts
{
    <script type="text/javascript">
        function Reset() {
            var code = $('#SearchCriterias_Code');
            var name = $('#SearchCriterias_Name');
            code.val('');
            name.val('');
        }
    </script>
}