MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Controllers/TransferOwnershipController.cs
//-----------------------------------------------------------------------------------
//  Developer   : Ashley Ow
//  File Name   : TransferOwnershipController.cs
//  Purpose     : Controller for Transfer Ownership Service Request
//  Version Control:
//  Version     Date         Change Made
//  1.0         12 Oct 2015  Controller created
//-----------------------------------------------------------------------------------

using Online.Registration.Web.Areas.ServiceRequest.DataAdapter;
using Online.Registration.Web.Areas.ServiceRequest.Enums;
using Online.Registration.Web.Areas.ServiceRequest.Helper;
using Online.Registration.Web.Areas.ServiceRequest.Interface;
using Online.Registration.Web.Areas.ServiceRequest.ViewModels;
using Online.Registration.Web.Areas.ServiceRequest.ViewModels.Common;
using Online.Registration.Web.CommonEnum;
using Online.Registration.Web.CustomExtension;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Online.Registration.Web.Areas.ServiceRequest.Controllers
{
    public class TransferOwnershipController : CommonController
    {
        [HttpGet]
        public ActionResult AjaxVerifyCustomer(SRVerifyCustomerVM vm)
        {
            if (!ModelState.IsValid){
                return Json(ModelState.ToErrorJson(), JsonRequestBehavior.AllowGet);
            }
            var idNo = vm.IdNo;
            var idType = vm.IdType;
            var isNew = vm.IsNew;
            //Get cust info
            CustInfoSource = new CustInfoByICAdapter(idType.ToIdTypeKenanEnumStr(), idNo);
            var custInfoVM = TheVMFactory.CreateCustInfoVM(CustInfoSource,ServiceTypes.PostpaidOnly);
            //Get bre info
            var breChecker = GetBreChecker(idType,idNo,CustInfoSource);
            var breErrors = breChecker.GetBreErrors();
            var newOrder = NewOrderVM as TransferOwnershipNewOrderVM;
            //set bre check status
            SetNewOwnerbreStatus(newOrder, breErrors);
            //Set in session to keep data sync
            if (isNew == false){
                newOrder.TransfereeBreErrors = breErrors;
                newOrder.NewCustIsExistCust = false;
                newOrder.ExistQueryCustomer = true;
            }
            else{
                newOrder.NewQueryCustomer = true;
                newOrder.NewCustIsExistCust = custInfoVM!=null && custInfoVM.IsExistingCust;
                newOrder.NewCustBreErrors = breErrors;
            }

            newOrder.TransfereeBiometricPass = breChecker.BiometricPass;

            if(custInfoVM!=null){
                if(isNew==false){
                    SetCustInfoToOrder(newOrder,custInfoVM);
                }
                else
                {
                    //let form posting to collect data
                }
            }
            if (custInfoVM != null && custInfoVM.MsisdnServiceInfoMap != null && custInfoVM.MsisdnServiceInfoMap.Count()>0)
            {
                newOrder.TransfereeMsisdnServiceInfoMap = custInfoVM.MsisdnServiceInfoMap;
                newOrder.TransfereeMsisdnList = custInfoVM.MsisdnServiceInfoMap.Keys.ToList();
            }
            //Output array of object with custinfo and breerrors
            return Json(new object[]{
                custInfoVM,
                breErrors.ToDictionary(n => n.Key.ToString(), n => n.Value)
            },
            JsonRequestBehavior.AllowGet);
        }

        private void SetNewOwnerbreStatus(TransferOwnershipNewOrderVM vm, Dictionary<BreType, string> breErrors)
        {
            vm.NewOwnerOutstandingCheckPass = !breErrors.ContainsKey(BreType.OutstandingCreditCheck);
            vm.NewOwnerTtlContractCheckPass = !breErrors.ContainsKey(BreType.ContractCheck);
            vm.NewOwnerTtlLineCheckPass = !breErrors.ContainsKey(BreType.TotalLineCheck);
            vm.NewOwnerWriteoffCheckPass = !breErrors.ContainsKey(BreType.WriteoffCheck);
            vm.NewOwnerBiometricPass = !breErrors.ContainsKey(BreType.Biometric);
        }

        private void SetCustInfoToOrder(TransferOwnershipNewOrderVM vm, SRCustInfo custInfoVM)
        {
            vm.Exist_CustName=custInfoVM.Name;
            vm.Exist_CustIDTypeId=int.Parse(custInfoVM.IdType.ToIDCardTypeValue());
            vm.Exist_CustIDNumber=custInfoVM.IdNum;
            vm.Exist_CustSalutation=custInfoVM.Salutation;
            vm.Exist_CustDOB=custInfoVM.Dob;
            vm.Exist_CustGender=custInfoVM.Gender;
            vm.Exist_CustLanguageID=custInfoVM.LanguageId;
            vm.Exist_CustNationalityID=custInfoVM.NationalityId;
            vm.Exist_CustRaceID=custInfoVM.RaceId;
            vm.Exist_CustEmail=custInfoVM.Email;
            vm.Exist_CustContactNumber=custInfoVM.ContactNum;
            vm.Exist_CustAlternateNumber=custInfoVM.AltContactNum;
            vm.Exist_CustAddressLine1=custInfoVM.BillAddLine1;
            vm.Exist_CustAddressLine2=custInfoVM.BillAddLine2;
            vm.Exist_CustAddressLine3=custInfoVM.BillAddLine3;
            vm.Exist_CustPostCode=custInfoVM.BillPostCode;
            vm.Exist_CustCity=custInfoVM.BillCity;
            vm.Exist_CustState=custInfoVM.BillState;
            vm.Exist_CustStateID=custInfoVM.BillStateId;
        }

        private IBreInfoProvider GetBreChecker(string idType, string idNo,ICustInfoProvider CustInfoSource)
        {
            //Only require ttl check, contract check, outstanding check, writeoff and biometric for thirdparty Auth
            var breChecker = new BreCheckerAdapter(
                idType,idNo,
                new[] {
                    BreType.TotalLineCheck,
                    BreType.ContractCheck,
                    BreType.OutstandingCreditCheck,
                    BreType.WriteoffCheck,
                    BreType.Biometric
                });
            //Init parameter to start breChecker
            breChecker.InitServices((CustInfoSource as CustInfoByICAdapter).GetAllServices());
            breChecker.InitBiometricParam((CustInfoSource as CustInfoByICAdapter).GetBiometricData());
            return breChecker;
        }
    }
}

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/NewOrderSummary.cshtml
@*-----------------------------------------------------------------------------------
    Date Created: 12 October 2015
    Developer   : Ashley Ow
    View Name   : NewOrderSummary.cshtml
    Purpose     : View to display the summary for Transfer Ownership Summary Service Request
    Version Control:
    Version     Date        Change Made
    1.0         12 Oct 2015  View created
    -----------------------------------------------------------------------------------*@

@using Online.Registration.Web.Helper
@using Online.Registration.Web.CustomExtension
@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipNewOrderSmVM

@using (Html.BeginForm("NewOrderSummary", "TransferOwnership", FormMethod.Post, new { id = "frmTransferOwnershipNewOrderSummary", enctype = "multipart/form-data", autocomplete = "off", autoCompleteType = "disable", @class = "overlayonsubmit", processmsg = "Loading" }))
{
<div class="container ipad-container">
    <div class="isell-base">
        <div class="row">
            <div class="col-sm-10">
                <h2 style="padding-left: 15px;">New Service Request Form:</h2>
                <h4 style="padding-left: 15px;">@Html.DisplayFor(n => n.HeaderCustName)</h4>
            </div>
            <div class="col-sm-1" style="right: 5px;">
                @Html.DisplayFor(n => n.NewOrder.BreErrors, "BreTooltip")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 green-bg">
                <p class="font-24">Transfer Ownership</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <ul class="steps" style="width: 300px;">
                    <li class="shownum">
                        <div class="num">1</div>
                        <p>My Details</p>
                    </li>
                    <li>
                        <div class="line"></div>
                    </li>
                    <li class="shownum">
                        <div  class="selected">2</div>
                        <p>Summary</p>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 border-top">
                <p class="summary-title">Summary</p>
                @Html.Partial("_ValidationSummary")
            </div>
        </div>
        <div class="row"></div>
        <!--Start Summary Detail-->
        @Html.Partial("_NewOrderSummaryDetailCustInfo", Model.NewOrder)
        <!--Start Term and condition-->
        <div class="row border-top">
            @Html.EditorFor(n=>n.TermAndCondition,"TermAndCondition")
        </div>
        <!--Start SignatureBox-->
        <div class="row border-bottom">
            <div class="col-sm-12">
                @Html.EditorFor(n => n.Signature, "SignatureBox")
            </div>
        </div>

        <!--Start New Owner Detail-->
        @Html.Partial("_TransferOwnershipNewOrderSummary2", Model)
        <!--Start Term and condition-->
        <div class="row border-top">
            @Html.EditorFor(n=>n.TermAndCondition_ForNewOwner,"TermAndCondition")
        </div>
        <!--Start SignatureBox-->
        <div class="row border-bottom">
            <div class="col-sm-12">
                @Html.EditorFor(n => n.Signature_ForNewOwner, "SignatureBox")
            </div>
        </div>

        <!--Start Navigation-->
        <footer class="nav-footer">
            <navi>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-1" id="back">
                            <div class="btn isell-btn" onclick="window.location.href='@Url.Action("NewOrderSummaryBack")'">&lt; Back</div>
                        </div>
                        <div class="col-sm-9" id="cancel">
                            <div class="btn isell-btn" data-toggle="modal" data-target="#cancel-pop">&lt; Cancel</div>
                        </div>
                        <div class="col-sm-2">
                            <div class="btn isell-next" id="nextButton" onclick="$('#submitBtn').click()">Submit<span>&gt;</span></div>
                            <input type="submit" value="Next" id="submitBtn" class="btn btn-default" style="display:none;" />
                        </div>
                    </div>
                </div>
            </navi>
        </footer>
    </div>
</div>
<!--Start modal section-->

@Html.Partial("_SummaryCancelModel")

<!--End modal section-->
}
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/col.css")" media="all" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/4cols.css")" media="all" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/tabcontent.css")" media="all" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/jquery-ui/jquery.ui.all.css")" />

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/_NewOrderDetailExistingAcc.cshtml
@*-----------------------------------------------------------------------------------
    Date Created: 11 October 2015
    Developer   : Ashley Ow
    View Name   : TransferOwnership.cshtml
    Purpose     : To capture the details for Transfer Ownership Service Request
    Version Control:
    Version     Date        Change Made
    1.0         11 Oct 2015  View created
    -----------------------------------------------------------------------------------*@

@using Online.Registration.Web.ViewModels.Common
@using Online.Registration.Web.CustomExtension
@using Newtonsoft.Json
@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipNewOrderVM

@functions{
    object getTbHtmlAttribute()
    {
        return new { @class = "form-control search-num" };
    }
    object getReadOnlyTbHtmlAttribute()
    {
        return new { @class = "form-control search-num readonly",@readonly="readonly" };
    }
}
<!-- Start Existing Address -->
<div class="row" id="trExistingAcc" style="padding-top:0">
    <div class="col-sm-12 form paddingOverall">
        <!-- Start Existing Address Identification -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Identification</p>
            </div>
            <div class="col-sm-3">
                <div class="input-group-btn number-type">
                    @Html.CustomDropDownListFor(model => model.Exist_CustIDTypeId, StaticListVM.Instance.IdTypList)
                </div>
            </div>
            <div class="col-sm-2">
                <p class="inner-label">*Number</p>
            </div>
            <div class="col-sm-3">
                <p class="inner-content">
                    @Html.TextBoxFor(model => model.Exist_CustIDNumber, getTbHtmlAttribute())
                    <button type="button" id="@Html.IdFor(n=>n.Exist_CustIDNumber)" class="btn btn-defadivt search-icon"></button>
                </p>
            </div>
            <div class="col-sm-1" id="@Html.IdFor(n=>n.TransfereeBreErrors)">
                @Html.DisplayFor(n => n.TransfereeBreErrors, "BreTooltip")
            </div>
        </div>

        <!-- Start Existing Address Name -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Name</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content">@Html.TextBoxFor(model => model.Exist_CustName, getReadOnlyTbHtmlAttribute())</p>
            </div>
        </div>

        <!-- Start Existing Address MSISDN -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*MSISDN</p>
            </div>
            <div class="col-sm-4">
                <div class="input-group-btn number-type">
                    @Html.CustomDropDownListFor(model => model.Exist_CustMSISDN,Model.TransfereeMsisdnList.ToSelectList())
                </div>
            </div>
        </div>

        <!-- Start Existing Address Account Number-->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Account No</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content">@Html.TextBoxFor(model => model.Exist_CustAccountNumber, getReadOnlyTbHtmlAttribute())</p>
            </div>
        </div>
    </div>
</div>

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/_NewOrderDetailNewAcc.cshtml
@*-----------------------------------------------------------------------------------
    Date Created: 11 October 2015
    Developer   : Ashley Ow
    View Name   : TransferOwnership.cshtml
    Purpose     : To capture the details for Transfer Ownership Service Request
    Version Control:
    Version     Date        Change Made
    1.0         11 Oct 2015  View created
    -----------------------------------------------------------------------------------*@

@using Online.Registration.Web.ViewModels.Common
@using Online.Registration.Web.CustomExtension
@using Newtonsoft.Json
@using Online.Registration.Web.Helper;
@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipNewOrderVM

@functions{
    object getTbHtmlAttribute()
    {
        return new { @class = "form-control search-num" };
    }
    object getReadOnlyTbHtmlAttribute()
    {
        return new { @class = "form-control search-num readonly", @readonly = "readonly" };
    }
}
<style>
    .dropdown-menu[display-id='@Html.IdFor(n=>n.New_DOBDay)Txt'],
    .dropdown-menu[display-id='@Html.IdFor(n=>n.New_DOBYear)Txt'],
    .dropdown-menu[display-id='@Html.IdFor(n=>n.New_CustSalutation)Txt'] {
        height: auto;
        max-height: 200px;
        overflow-x: hidden;
    }
</style>
<!-- Start New Acc section -->
<div class="row" id="trNewAcc" style="padding-top:0">
    <div class="col-sm-12 form paddingOverall" >
        <!-- Start New Address ID Number -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Identification</p>
            </div>
            <div class="col-sm-3">
                <div class="input-group-btn number-type">
                    @Html.CustomDropDownListFor(model => model.New_CustIDTypeId, StaticListVM.Instance.IdTypList)
                </div>
            </div>
            <div class="col-sm-2">
                <p class="inner-label">*Number</p>
            </div>
            <div class="col-sm-3">
                <p class="inner-content">
                    @Html.TextBoxFor(model => model.New_CustIDNumber, getTbHtmlAttribute())
                    <button type="button" id="@Html.IdFor(n=>n.New_CustIDNumber)" class="btn btn-defadivt search-icon"></button>
                </p>
            </div>
            <div class="col-sm-1" id="@Html.IdFor(n=>n.NewCustBreErrors)">
                @Html.DisplayFor(n => n.NewCustBreErrors, "BreTooltip")
            </div>
        </div>

        <!-- Start New Address Salutation -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">Salutation</p>
            </div>
            <div class="col-sm-4">
                <div class="input-group-btn number-type">
                    @Html.CustomDropDownListFor(model => model.New_CustSalutation, StaticListVM.Instance.SalutationList)
                </div>
            </div>
        </div>

        <!-- Start New Address Account Name -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Full name as per ID</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content lock-if-maxiscust">@Html.TextBoxFor(model => model.New_CustName, getTbHtmlAttribute())</p>
            </div>
        </div>

        <!-- Start New Address Account DOB -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Date Of Birth</p>
            </div>
            <!-- DOB (Year) -->
            <div class="col-sm-2">
                <p class="inner-label">Year</p>
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_DOBYear, Util.GetYearList(18))
                </div>
            </div>
            <!-- DOB (Month) -->
            <div class="col-sm-2">
                <p class="inner-label">Month</p>
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_DOBMonth, Util.GetMonthList())
                </div>
            </div>
            <!-- DOB (Day) -->
            <div class="col-sm-2">
                <p class="inner-label">Day</p>
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_DOBDay, Util.GetDayList())
                </div>
            </div>
        </div>

        <!-- Start New Address Account Gender -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Gender</p>
            </div>
            <div class="col-sm-4 lock-if-maxiscust">
                @Html.RadioButtonFor(model => model.New_CustGender, "M", new { id = "rbGenderMale", @checked = "True", @class = "form-radio alert" }) <label for="rbGenderMale" class="stock-label">Male</label>
                @Html.RadioButtonFor(model => model.New_CustGender, "F", new { id = "rbGenderFemale", @class = "form-radio alert" }) <label for="rbGenderFemale" class="stock-label">Female</label>
            </div>
        </div>

        <!-- Start New Address Account Language -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Preferred Language</p>
            </div>
            <div class="col-sm-4">
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_CustLanguageID, StaticListVM.Instance.LanguageList)
                </div>
            </div>
        </div>

        <!-- Start New Address Account Nationality -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Nationality</p>
            </div>
            <div class="col-sm-4">
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_CustNationalityID, StaticListVM.Instance.NationalityList)
                </div>
            </div>
        </div>

        <!-- Start New Address Account Race -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Race</p>
            </div>
            <div class="col-sm-4">
                <div class="input-group-btn number-type lock-if-maxiscust">
                    @Html.CustomDropDownListFor(model => model.New_CustRaceID, StaticListVM.Instance.RaceList)
                </div>
            </div>
        </div>

        <!-- Start New Address Account Email -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">Email</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content">@Html.TextBoxFor(model => model.New_CustEmail, getTbHtmlAttribute())</p>
            </div>
        </div>

        <!--Start New Address Account Contact Number -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">*Contact Number</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content">@Html.TextBoxFor(model => model.New_CustContactNumber, getTbHtmlAttribute())</p>
            </div>
        </div>

        <!-- Start New Address Account Alternate Contact Number -->
        <div class="row">
            <div class="col-sm-3">
                <p class="inner-label">Alternate Contact Number</p>
            </div>
            <div class="col-sm-4">
                <p class="inner-content">@Html.TextBoxFor(model => model.New_CustAlternateNumber, getTbHtmlAttribute())</p>
            </div>
        </div>
    </div>

    <div class="col-sm-12 form border-top even paddingOverall" style="margin-bottom: 0;">
            <p class="device-title">Billing Address</p>
            <!-- Start New Address Line 1 -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label">*Address</p>
                </div>
                <div class="col-sm-4">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustAddressLine1, getTbHtmlAttribute())</p>
                </div>
            </div>

            <!-- Start New Address Line 2 -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label"></p>
                </div>
                <div class="col-sm-4">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustAddressLine2, getTbHtmlAttribute())</p>
                </div>
            </div>

            <!-- Start New Address Line 3 -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label"></p>
                </div>
                <div class="col-sm-4">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustAddressLine3, getTbHtmlAttribute())</p>
                </div>
            </div>

            <!-- Start New Address Postcode -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label">*Postcode</p>
                </div>
                <div class="col-sm-3">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustPostCode, getTbHtmlAttribute())</p>
                </div>
                <div class="col-sm-3">
                    <p class="inner-content" id="PostcodeValidationMessage"></p>
                </div>
            </div>

            <!-- Start New Address City -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label">*City</p>
                </div>
                <div class="col-sm-4">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustCity, getReadOnlyTbHtmlAttribute())</p>
                </div>
            </div>

            <!-- Start New Address State -->
            <div class="row">
                <div class="col-sm-3">
                    <p class="inner-label">*State</p>
                </div>
                <div class="col-sm-4">
                    <p class="inner-content">@Html.TextBoxFor(model => model.New_CustState, getReadOnlyTbHtmlAttribute())</p>
                </div>
            </div>
    </div>
</div>

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/_PrintOrderDetailSignature.cshtml
@using Online.Registration.Web.Helper

@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipPrintOrderVM
@{
    string orderLabel = ViewData["OrderLabel"].ToString();
    orderLabel = string.IsNullOrEmpty(orderLabel) ? "E" : orderLabel;
}
<table class="rfTable" width="670px" align="center">
    <tbody>
        <tr>
            <td colspan="4" style="background-color: Black; color: White; text-transform: uppercase; font-weight: bolder; font-size: small;">
                <div>@orderLabel. For Office Use Only</div>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <table>
                    <tbody>
                        <tr>
                            <td style="width: 175px">
                                <b>*Sales Code - Dealer Outlet</b>
                            </td>
                            <td>@Html.DisplayFor(n => n.BranchNameDisplay)</td>
                        </tr>
                        <tr>
                            <td>
                                <b>*Sales Staff Code</b>
                            </td>
                            <td>@Html.DisplayFor(n => n.StaffCodeDisplay)</td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="4">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" align="left">
                <br/>
                <div style="position: relative">
                    <div class="signature-backgound">
                        <img src="@Url.Content("~/Content/images/maxis_use_only_s.png")" style="position: absolute; z-index: -1;border-bottom:solid 1px black;">
                        <table>
                            <tr>
                                <td height="200px" width="400px" valign="middle" align="center" style="vertical-align:middle;">
                                    @Html.DisplayFor(n => n.SignSvg, "SignatureBase64")
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </td>
            <td colspan="2" align="left"><br /></td>
        </tr>
        <tr>
            <td colspan="2">
                <br />
                Current Owner's Signature
                <br />
                Date @Util.FormatDateTime(Model.SignDt)
            </td>
        </tr>
        <tr>
            <td colspan="2" align="left">
                <br/>
                <div style="position: relative">
                    <div class="signature-backgound">
                        <img src="@Url.Content("~/Content/images/maxis_use_only_s.png")" style="position: absolute; z-index: -1;border-bottom:solid 1px black;">
                        <table>
                            <tr>
                                <td height="200px" width="400px" valign="middle" align="center" style="vertical-align:middle;">
                                    @Html.DisplayFor(n => n.NewOwnerSignature.SignSvg, "SignatureBase64")
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </td>
            <td colspan="2" align="left"><br /></td>
        </tr>
        <tr>
            <td colspan="2">
                <br />
                New Owner's Signature
                <br />
                Date @Util.FormatDateTime(Model.SignDt)
            </td>
        </tr>
                <tr>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/_TransferOnwershipViewOrderDetail.cshtml
@using Online.Registration.Web.Helper;
@using Online.Registration.Web.CustomExtension;

@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipViewOrderVM

@Html.Partial("_ViewOrderDetailCustInfo", Model)

MobilityProd/Online.Registration.Web/Areas/ServiceRequest/Views/TransferOwnership/_TransferOwnershipNewOrderSummary.cshtml
@using Online.Registration.Web.CustomExtension;
@using Online.Registration.Web.Helper;

@model Online.Registration.Web.Areas.ServiceRequest.ViewModels.TransferOwnershipNewOrderSmVM

@Html.Partial("_NewOrderSummaryDetailCustInfo", Model.NewOrder)