MobilityProd/Online.Registration.Web/Controllers/SuppLineController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using log4net;
using Online.Registration.DAL;
using Online.Registration.DAL.Models;
using Online.Registration.Web.CatalogSvc;
using Online.Registration.Web.CommonEnum;
using Online.Registration.Web.ContentRepository;
using Online.Registration.Web.Helper;
using Online.Registration.Web.KenanSvc;
using Online.Registration.Web.Models;
using Online.Registration.Web.RegistrationSvc;
using Online.Registration.Web.Properties;
using Online.Registration.Web.SubscriberICService;
using Online.Registration.Web.ViewModels;
using Online.Web.Helper;
using SNT.Utility;

namespace Online.Registration.Web.Controllers
{
	[CustomErrorHandlerAttr(View = "GenericError")]
	[SessionAuthenticationAttribute]
	public class SuppLineController : Controller
	{
		#region Member Declarations
		private static readonly ILog Logger = LogManager.GetLogger(typeof(RegistrationController));
		private string ProcessingMsisdn = string.Empty;
		private bool sharingQuotaFeature = ConfigurationManager.AppSettings["SharingSupplementaryFlag"].ToBool();
		#endregion


		#region Action Methods


		[Authorize]
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public ActionResult CheckMISMLines(string msisdn)
		{
			string Message = string.Empty;
			PrinSupEaiHeader header = null;
			retrievegetPrinSuppResponse response = null;
			header = null;
			response = null;
			bool value = false;
			string ExternalID = string.Empty;
			string tblId = string.Empty;
			if (msisdn != null)
			{
				string[] strAccountDtls = msisdn.Split(',');
				ExternalID = strAccountDtls[1].ToString2();
				tblId = strAccountDtls[4].ToString2();
			}
			if (tblId == "SeconList")
			{
				using (var PrinSupproxy = new PrinSupServiceProxy())
				{

					var req = new SubscribergetPrinSuppRequest();
					req.eaiHeader = header;
					req.msisdn = ExternalID;
					DateTime dtReq = DateTime.Now;

					response = PrinSupproxy.getPrinSupplimentarylines(req);
					var count = response.itemList.ToList().Count();
					if (count != 0)
					{
						value = true;
						Message = "This customer unable to add supplementory Lines";
					}
				}
			}
			else
			{
				using (var PrinSupproxy = new PrinSupServiceProxy())
				{

					var req = new SubscribergetPrinSuppRequest();
					req.eaiHeader = header;
					req.msisdn = ExternalID;
					DateTime dtReq = DateTime.Now;

					response = PrinSupproxy.getPrinSupplimentarylines(req);
					var count = response.itemList.ToList().Count();
					if (count != 0)
					{
						value = true;
						Message = "This customer unable to add supplementory Lines";
					}
				}
			}


			return Json(new { Success = value, Message });
		}

		[Authorize(Roles = "MREG_W,MREG_C,MREG_DSV,MREG_DSA,DREG_N,DREG_C,MREG_DC,MREG_DAI,MREG_DAC")]
		public ActionResult SecondaryLinePlan(int? type, bool isBack = false)
		{
			Session["PrimarySim"] = null;
			Session[SessionKey.SelectedComponents.ToString()] = null;
			Session["MobileRegType"] = "Planonly";
			if (type > 0)
				ResetAllSession(type);
			if (!isBack)
				WebHelper.Instance.ClearSubLineSession();
			Session["RegMobileReg_SublineSummary"] = ConstructOrderSummary(fromSubline: false);
			var sublinePkgVM = new SublinePackageVM();
			sublinePkgVM.PackageVM = GetAvailablePackagesForSecondaryLine(false);
			sublinePkgVM.SelectedMobileNumber = Session["RegMobileSub_MobileNo"] == null ? new List<string>() : (List<string>)Session["RegMobileSub_MobileNo"];
			sublinePkgVM.NoOfDesireMobileNo = Properties.Settings.Default.NoOfDesireMobileNo;

			Session["RegMobileReg_SublineSummary"] = ConstructOrderSummary(false);
			Session["VasGroupIds_Seco"] = null;
			PersonalDetailsVM objCurDetails = new PersonalDetailsVM();

			sublinePkgVM.PersonalDetailsVM = objCurDetails;
			return View(sublinePkgVM);
		}

		[Authorize]
		[HttpPost]
		public ActionResult SecondaryLinePlan(FormCollection collection, SublinePackageVM sublinePkgVM)
		{
			try
			{
				if (collection["submit1"].ToString2().ToUpper() == "NEXT")
				{
					// selected different Sub Plan
					if (Session["RegMobileReg_PkgPgmBdlPkgCompID"].ToInt() != sublinePkgVM.PackageVM.SelectedPgmBdlPkgCompID)
					{
						Session["RegMobileReg_PkgPgmBdlPkgCompID"] = sublinePkgVM.PackageVM.SelectedPgmBdlPkgCompID;
						Session["SelectedPlanID"] = sublinePkgVM.PackageVM.SelectedPgmBdlPkgCompID;
					}

					var mobileNos = new List<string>();

					for (int i = 0; i < Properties.Settings.Default.NoOfDesireMobileNo; i++)
					{
						mobileNos.Add(collection["txtMobileNo_" + i].ToString2());
					}

					Session["RegMobileSub_MobileNo"] = mobileNos;
				}
				else if (collection["submit1"].ToString2().ToLower() == "back")
				{
					return RedirectToAction("AddSuppLine");
				}
				else
				{
					return RedirectToAction("SecondaryLineVAS");
				}
			}
			catch (Exception ex)
			{
				WebHelper.Instance.LogExceptions(this.GetType(), ex);
				throw ex;
			}
			return RedirectToAction("SecondaryLineVAS");
		}


		[Authorize(Roles = "MREG_W,MREG_C,MREG_DSV,MREG_DSA,DREG_N,DREG_C,MREG_DC,MREG_DC,MREG_DAI,MREG_DAC")]
		public ActionResult SecondaryLineVAS()
		{

			ValueAddedServicesVM Lstvam = new ValueAddedServicesVM();
			ValueAddedServicesVM Lstvam2 = new ValueAddedServicesVM();
			Session["RegMobileReg_OrderSummary"] = null;
			Session["RegMobileReg_SublineSummary"] = null;
			Session["RegMobileReg_VasNames"] = null;
			Session["RegMobileReg_VasIDs"] = null;
			Session["RegMobileReg_SublineVM"] = null;
			Session["RegMobileReg_VirtualMobileNo_Sec"] = null;

			if (Session["PPID"].ToString2() != string.Empty)
			{
				if (!ReferenceEquals(Session["RedirectURL"], null))
				{
					Session.Contents.Remove("RedirectURL");
				}

				GetRegActionStepForSecondaryPlan(SecondaryLineRegistrationSteps.Vas.ToInt());
				if (Session["RegMobileReg_PkgPgmBdlPkgCompID"] == null || Session["RegMobileReg_PkgPgmBdlPkgCompID"] == string.Empty)
				{
					Session["RegMobileReg_PkgPgmBdlPkgCompID"] = Session["GuidedSales_PkgPgmBdlPkgCompID"];
				}
				Session["RegMobileReg_OrderSummary"] = ConstructOrderSummary(fromSubline: false);
				string MobileRegType = "planonly";

				OrderSummaryVM orderVM = (OrderSummaryVM)Session["RegMobileReg_OrderSummary"];

				Int32 Selecpgmid = (orderVM.SelectedPgmBdlPkgCompID != 0 && orderVM.SelectedPgmBdlPkgCompID != null) ? orderVM.SelectedPgmBdlPkgCompID : Session["RegMobileReg_PkgPgmBdlPkgCompID"].ToInt();

				Lstvam = WebHelper.Instance.GetAvailablePackageComponents(Selecpgmid, ref ProcessingMsisdn, isMandatory: false, fromSuppline: true);

				Session["RegMobileReg_OrderSummary"] = ConstructOrderSummary(fromSubline: false);
				var selectedCompIDs = new List<int>();
				List<AvailableVAS> lstvas = new List<AvailableVAS>();


				lstvas.AddRange(orderVM.VasVM.MandatoryVASes);

				for (int i = 0; i < orderVM.Sublines.Count(); i++)
				{
					for (int j = 0; j < orderVM.Sublines[i].SelectedVasNames.Count; j++)
					{
						lstvas.Add(new AvailableVAS() { PgmBdlPkgCompID = orderVM.Sublines[i].SelectedVasIDs[j], ComponentName = orderVM.Sublines[i].SelectedVasNames[j].ToString2() });
					}

				}


				for (int i = 0; i < lstvas.Count(); i++)
				{
					selectedCompIDs.Add(lstvas[i].PgmBdlPkgCompID);
				}



				Lstvam2.ContractVASes.AddRange(Lstvam.ContractVASes);

				Lstvam2.AvailableVASes.AddRange(Lstvam.AvailableVASes);

				Session["RegMobileReg_VasNames"] = orderVM.VasVM.MandatoryVASes;

				/* For Mandatory packages */
				Session["vasmandatoryids"] = string.Empty;
				using (var proxy = new CatalogServiceProxy())
				{

					BundlepackageResp respon = new BundlepackageResp();

					respon = proxy.GetMandatoryVas(Convert.ToInt32(Session["RegMobileReg_PkgPgmBdlPkgCompID"]));

					for (int i = 0; i < respon.values.Count(); i++)
					{

						if (respon.values[i].Plan_Type == Properties.Settings.Default.Master_Component)
						{
							Lstvam = WebHelper.Instance.GetAvailablePackageComponents_PC_MC_DC(Convert.ToInt32(respon.values[i].BdlDataPkgId), respon.values[i].Plan_Type, isMandatory: false, fromSuppLine: true);

							Session["intmandatoryidsval"] = respon.values[i].BdlDataPkgId;

							Lstvam2.AvailableVASes.AddRange(Lstvam.AvailableVASes);
						}

						if (respon.values[i].Plan_Type == Properties.Settings.Default.CompType_DataCon)
						{
							Lstvam = WebHelper.Instance.GetAvailablePackageComponents_PC_MC_DC(Convert.ToInt32(respon.values[i].BdlDataPkgId), respon.values[i].Plan_Type, isMandatory: false, fromSuppLine: true);
							List<int> Finalintvalues = null;
							if (Session["RegMobileReg_Type"].ToInt() == 1)
							{
								List<PkgDataPlanId> values = proxy.getFilterplanvalues(1).values.ToList();

								string modelid = ((OrderSummaryVM)(Session["RegMobileReg_OrderSummary"])).ModelID.ToString();

								Finalintvalues = values.Where(mid => mid.Modelid == "0").Select(a => a.BdlDataPkgId).ToList();
                                if (Finalintvalues.Count() == 0)
                                {
                                    Finalintvalues = values.Where(mid => mid.Modelid == modelid).Select(a => a.BdlDataPkgId).ToList();
                                }

							}

							List<PkgDataPlanId> valuesplan = proxy.getFilterplanvalues(2).values.ToList();

							Finalintvalues = valuesplan.Select(a => a.BdlDataPkgId).ToList();

							var finalfiltereddatacontracts = from e in Lstvam.AvailableVASes

															 join m in Finalintvalues on Convert.ToInt32(e.PgmBdlPkgCompID) equals Convert.ToInt32(m)

															 select new AvailableVAS()
															 {
																 ComponentName = e.ComponentName,
																 PgmBdlPkgCompID = e.PgmBdlPkgCompID,
																 Price = e.Price,
																 Value = e.Value,

MobilityProd/Online.Registration.Web/Views/SuppLine/PaymentDetails.cshtml
@using Online.Registration.Web.ViewModels
@using Online.Registration.Web.Helper;
@using Online.Registration.Web.Properties;
@using SNT.Utility;
@{
    ViewBag.Title = "Payment Details";
}
@model Online.Registration.Web.ViewModels.CustomerPaymentDetailsInfo
@{Online.Registration.Web.ViewModels.OrderSummaryVM MobileRegOrderSummary = (OrderSummaryVM)Session["RegMobileReg_OrderSummary"];}
<div class="vwHeader">
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div class="viewInnerBody">
    @Html.ValidationSummary(true, "")
    @using (Html.BeginForm("PaymentDetails", "SuppLine", FormMethod.Post, new { id = "frmPaymentDetails", @class = "overlayonsubmit", processmsg = "Loading" }))
    {

        string OrderId = string.Empty;
        string Amount = string.Empty;
        if (!ReferenceEquals(ViewBag.OrderId, null))
        {
            OrderId = Convert.ToString(ViewBag.OrderId);
            Session["OrderId"] = ViewBag.OrderId;
        }
        if (!ReferenceEquals(ViewBag.Amount, null))
        {
            Amount = ViewBag.Amount;
            Session["Amount"] = ViewBag.Amount;
        }
        <table width="500px">
            <tr>
                <td>
                    <b>@Html.LabelFor(model => model.CustomerInfo.PayModeID)</b>
                </td>
                <td>@(Html.Telerik().DropDownListFor(model => model.CustomerInfo.PayModeID).BindTo(Util.GetList(RefType.CustomerInfoPaymentMode, defaultValue: "")))
                </td>
            </tr>
            @*<tr style="display:none;">
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.CardTypeID)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@(Html.Telerik().DropDownListFor(model => model.CustomerInfo.CardTypeID).BindTo(Util.GetList(RefType.CustomerInfoCardType, defaultValue: "")))</div>
                </td>
            </tr>
            <tr style="display:none;">
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.CardNo)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@Html.TextBoxFor(model => model.CustomerInfo.CardNo)&nbsp;&nbsp;eg.4234990256302271
                    </div>
                </td>
            </tr>
            <tr style="display:none;">
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.CardExpiryDate)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@Html.TextBoxFor(model => model.CustomerInfo.CardExpiryDate)&nbsp;&nbsp;eg.
                        MMYY</div>
                </td>
            </tr>
            <tr style="display:none;">
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.NameOnCard)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@Html.TextBoxFor(model => model.CustomerInfo.NameOnCard, new { @class = "uppercase", onchange = "toUpperCase(this)" })</div>
                </td>
            </tr>
            <tr style="display:none;">
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.CVV)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@Html.TextBoxFor(model => model.CustomerInfo.CVV)</div>
                </td>
            </tr>*@
            <tr>
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.OrderID)</b></div>
                </td>
                <td>
                    <div class="autoBilling">@OrderId</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="autoBilling">
                        <b>@Html.LabelFor(model => model.CustomerInfo.Amount)</b></div>
                </td>
                <td>
                    <div class="autoBilling">
                        RM@(Amount)
                    </div>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <div class="autoBilling">
                        <button type="button" class="button-cancel" onclick="navigate();" />
                    </div>
                </td>
                <td>
                    @if (Convert.ToInt32(Amount) != 0)
                    {
                        <div class="autoBilling">
                            <input type="submit" value="" onclick="return submitform();" class="button-submit" />
                        </div>
                    }
                </td>
            </tr>
        </table>
    }
</div>
@section Scripts{
    <script type="text/javascript">

        function submitform() { 
        var PaymentID = $('#CustomerInfo_PayModeID').val();

        if (PaymentID == "") {
            alert("The Payment Mode * field is required.");
            return false;
        }
        
        else {
            return true;
        }
        }

        function navigate() {
            window.location = "MobileRegSummary/" + @(ViewBag.OrderId);
        }
    </script>
    }

MobilityProd/Online.Registration.Web/Views/SuppLine/PaymentDetailsSuccess.cshtml
@{
    ViewBag.Title = "Payment Details Success";
}
<div class="vwHeader">
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div class="viewInnerBody">
    @Html.ValidationSummary(true, "")
    @using (Html.BeginForm())
    {

        string Paymentstatus = string.Empty;
        if (!ReferenceEquals(ViewBag.Paymentstatus, null))
        {
            Paymentstatus = Convert.ToString(ViewBag.Paymentstatus);
        }
         
        <h2>
        @if (Paymentstatus == "Success")
        {
            <text> Payment Success ! </text>
        }
        else if (Paymentstatus == "Failed")
        {
            <text> Payment Failed !</text>
        }
        
        </h2>
        <p class="p2">Click <span><a href="../">Here</a></span> to go back<br /></p>
    }
</div>

MobilityProd/Online.Registration.Web/Views/SuppLine/SecondaryLineRegBreFail.cshtml
@using Online.Registration.Web.Helper;
@{
    ViewBag.Title = "Business Rule Check Failed";
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";
}
@model int
<div>
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div>
    <h2>
        Registration has been closed, due to business rule check got failed.</h2>
</div>

MobilityProd/Online.Registration.Web/Views/SuppLine/SecondaryLineRegCanceled.cshtml
@using Online.Registration.Web.Helper;
@{
    ViewBag.Title = "Cancel Registration";
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";
}
@model int
<div>
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div>
    <h3>
        Registration has been canceled successfully.</h3>
    <h3>
        Click
        @Html.ActionLink("HERE", "SecondaryLineRegSummary", new { regID = Html.DisplayForModel() }, new { style = "color:#5fb848;font-weight:bold;text-decoration:none" })
        to view registration@* or 
            <a href="/Registration/PrintMobileRF?id=@Model" target="_blank" style="text-decoration:none" >
                <img alt="" src="../../Content/images/Print.gif" /> Print
            </a>
        the registration form*@.
    </h3>
</div>

MobilityProd/Online.Registration.Web/Views/SuppLine/SecondaryLineRegFail.cshtml
@using Online.Registration.Web.Helper;
@{
    ViewBag.Title = "Registration Failed";
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";
    var cancelURL = Url.Content("~/Home/IndexNew");
}
@model int
<div>
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
@using (Html.BeginForm("SecondaryLineRegFail", "SuppLine", FormMethod.Post, new { id = "frmMobileRegFail", @class = "overlayonsubmit", processmsg = "Loading" }))
{
    <div>
        @Html.Hidden("TabNumber")
        <h3>&nbsp;&nbsp;Technical issue encountered, please click cancel button and try again. If the issue persists, please contact ISDHDESK@maxis.com.my.</h3>
        <table width="100%">
            <tr>
                <td align="right" valign="bottom">
                    @*<input class="cancel backButton" type="submit" value="<" onclick="$('#TabNumber').val(6);" />*@
                    <input type="button" class="cancel backButton" id="btnCancel" value="< Cancel" />
                </td>
            </tr>
        </table>
        @*<h2>Registration has been failed due to an internal error. Please retry your registration…</h2>*@
        @*<h3>
            Registration was not successful due to data inconsistency. Please retry to register
            by clicking back button</h3>*@
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#btnCancel').click(function (e) {
            e.preventDefault();
            window.location.href = '@cancelURL';
        });
    });
</script>

MobilityProd/Online.Registration.Web/Views/SuppLine/SecondaryLineRegSuccess.cshtml
@using Online.Registration.Web.Helper;
@using SNT.Utility;
@using Online.Registration.Web.Properties;
@{
    ViewBag.Title = "Submit Registration";
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";
}
@model int
<div>
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div>
    @if (System.Configuration.ConfigurationManager.AppSettings["ToEmail"].ToString2() == "Y" && !Roles.IsUserInRole("MREG_CUSR"))
    {
@*VLT CHANGED CODE 21stFEB *@
        <h3>
            Registration has been submitted successfully and an email has been sent to you…</h3>
@*VLT CHANGED CODE 21stFEB *@
    }
    else
    {
        <h3>
            Registration has been submitted successfully.</h3>
    }
    <h4>
        Click
        @Html.ActionLink("HERE", "SecondaryLineRegSummary", new { regID = Html.DisplayForModel() }, new { style = "color:#5fb848;font-weight:bold;text-decoration:none" })
        to view registration or <a href="@(Url.Content("~/Registration/PrintMobileRF?id=" + Model))" target="_blank" style="text-decoration:none" >
            <img alt="Print" src='@Url.Content("~/Content/images/Print.gif")' style="border:0" />
            Print </a>the registration form.
    </h4>
</div>

MobilityProd/Online.Registration.Web/Views/SuppLine/SelectAccessory.cshtml
@using Online.Registration.Web.Helper;
@model Online.Registration.Web.ViewModels.AccessoriesVM

@{
    ViewBag.Title = "Maxis iSELL Portal - Accessory";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
    var viewBagAccessory = new ViewDataDictionary();
    viewBagAccessory.Add("imageURLForAccessory", ViewBag.imageURLForAccessory);
    viewBagAccessory.Add("ErrorMessage", ViewBag.ErrorMessage);
    viewBagAccessory.Add("HardStopMessage", ViewBag.HardStopMessage);
}

@using (Html.BeginForm("SelectAccessory", "SuppLine", FormMethod.Post, new { id = "frmSelectAccessory", @class = "overlayonsubmit", processmsg = "Loading" }))
{
    @Html.Hidden("TabNumber");
    @Html.Hidden("ButtonClicked");
    <div class="container ipad-container">
        <div class="isell-base">
            @{
                Html.RenderPartial("_AccountHolderName");
            }
            <div class="row">
                <div class="col-sm-12 green-bg">
                    <p class="font-24">
                        Select Accessory
                    </p>
                </div>
            </div>
            @{ 
                Html.RenderPartial("_OrderFlow");
            }
            <div class="row">
                <div class="col-sm-12 grey-bg">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs line-tab" role="tablist">
                        <li class="active">
                            <a href="#principle" role="tab" data-toggle="tab">@Constants.SUPPLEMENTARY_LINE</a>
                            <span class="active-green-arrow"></span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane active" id="principle">
                            <div class="row">
                                <div class="col-sm-12">
                                    <p class="device-title">
                                        <span>Step 01b:</span> Choose the accessories to go with your device
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <p class="font-16">@(ViewBag.GSTnotif)</p>
                                </div>
                            </div>
                            <div class="col-sm-10 error-msg">
                                <p id="errorMsgPanel" style="padding-left:15px;color:#ff0000;">@(ViewBag.SelectDevicePlanError)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row border-top">
                <div class="col-sm-9 col-xs-9" style="display:inline-block; height:100%; font-size:16px; padding-right:0px;">
                    @Html.Partial("_SearchAccessory", Model, viewBagAccessory)
                </div>
                <div class="col-sm-3 col-xs-3" style="width:28%;">
                    @{
                        var viewBagValue = new ViewDataDictionary();
                        viewBagValue.Add("GSTMark", ViewBag.GSTMark);
                        Html.RenderPartial("_OrderSummaryNew", viewBagValue);
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 process-btn">
                    <footer>
                        <navi>
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-sm-1" id="back">
									    <div class="btn isell-btn" id="btnNext" onclick="$('#TabNumber').val(12);$('#frmSelectAccessory').submit();">< Back</div>
								    </div>
							        <div class="col-sm-9" id="cancel">
								        <div class="btn isell-btn"  id="btnNext" data-toggle="modal" data-target="#cancel-pop">< Cancel</div>
							        </div>
                                    <div class="col-sm-2">
                                        <div class="btn isell-next" id="btnNextPage">Next <span>></span></div>
                                    </div>
                                </div>
                            </div>
                        </navi>
                    </footer>
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    var searchAccessoryURL = '@(Url.Content("~/Registration/SearchAccessory"))';
    var addAccessoryURL = '@(Url.Content("~/Registration/AddAccessory"))';
    var removeAccessoryURL = '@(Url.Content("~/Registration/removeAccessory"))';
    var loadAccessoryURL = '@(Url.Content("~/Registration/LoadAccessory"))';

    $('#btnNextPage').click(function () {
        debugger;
        $('#TabNumber').val(3);
        $('#submitType').val('');

        if (validateAccessoryFinancingPrice()) {
            $('#frmSelectAccessory').submit();
        }
    });
</script>
<script type="text/javascript" language="javascript" src="@Url.Content("~/Scripts/js2/accessory.js")"></script>