MobilityProd/Online.Registration.Web/Controllers/NewLineController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using log4net;
using Online.Registration.DAL.Models;
using Online.Registration.Web.CatalogSvc;
using Online.Registration.Web.CommonEnum;
using Online.Registration.Web.ContentRepository;
using Online.Registration.Web.Helper;
using Online.Registration.Web.KenanSvc;
using Online.Registration.Web.Models;
using Online.Registration.Web.Properties;
using Online.Registration.Web.RegistrationSvc;
using Online.Registration.Web.SubscriberICService;
using Online.Registration.Web.ViewModels;
using Online.Web.Helper;
using SNT.Utility;

namespace Online.Registration.Web.Controllers
{
    //[HandleError(View = "GenericError")]
    [CustomErrorHandlerAttr(View = "GenericError")]
    [SessionAuthenticationAttribute]
    public class NewLineController : Controller
    {
        //
        // GET: /NewLine/
        #region Member Declarations
        private static readonly ILog Logger = LogManager.GetLogger(typeof(NewLineController));
        #endregion

        private void LogException(Exception ex)
        {
            Logger.DebugFormat("Exception: {0}", ex.Message);
        }

        #region Action Methods
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult AddNewLine()
        {
            var dropObj = new DropFourObj();
            Session[SessionKey.DropFourObj.ToString()] = dropObj;
            Session[SessionKey.FromPromoOffer.ToString()] = null;
            Session[SessionKey.MarketCode.ToString()] = null;
            Session[SessionKey.SelectedPlanID_Seco.ToString()] = null;
            Session[SessionKey.VasGroupIds.ToString()] = null;
            Session[SessionKey.SelectedPlanID.ToString()] = null;
            Session[SessionKey.OfferId.ToString()] = null;
            Session[SessionKey.Discount.ToString()] = null;
            Session[SessionKey.RegMobileReg_MainDevicePrice.ToString()] = null;
            Session[SessionKey.RegMobileReg_OrderSummary.ToString()] = null;
            Session[SessionKey.RegMobileReg_OfferDevicePrice.ToString()] = null;
            Session["vasBackClick"] = null;
            Session[SessionKey.RegMobileReg_PkgPgmBdlPkgCompID.ToString()] = null;
            Session[SessionKey.RegMobileReg_PkgPgmBdlPkgCompID_Seco.ToString()] = null;
            Session[SessionKey.RegMobileReg_VirtualMobileNo_Sec.ToString()] = null;
            Session[SessionKey.RegMobileReg_MobileNo.ToString()] = null;
            Session[SessionKey.SelectedPlanID_Seco.ToString()] = null;
            Session[SessionKey.SimType.ToString()] = null;
            Session[SessionKey.Condition.ToString()] = null;
            Session["AccountHolder"] = null;
            Session["_componentViewModel"] = null;
            Session[SessionKey.AccountCategory.ToString()] = null;
            Session[SessionKey.MarketCode.ToString()] = null;
            Session["SMEIPARENTID"] = null;
            WebHelper.Instance.ResetDepositSessions();

            #region added by Rajeswari
            if (!ReferenceEquals(Session[SessionKey.RegMobileReg_OrderSummary.ToString()], null))
            {
                Session[SessionKey.RegMobileReg_OrderSummary.ToString()] = null;
            }
            #endregion

            retrieveAcctListByICResponse AcctListByICResponse = null;
            SupplementaryListAccounts SuppListAccounts = null;

            ///BELOW ERROR MIGHT GET POPULATED FROM TARGET PAGE
            if (!ReferenceEquals(TempData["Error"], null))
            {
                ModelState.AddModelError("Error", "Select an account");
            }

            ///CHECK PPID AND PPIDINFO SESSIONS
            if ((!ReferenceEquals(Session[SessionKey.PPID.ToString()], null) && "E".Equals(Convert.ToString(Session[SessionKey.PPID.ToString()]))) && !ReferenceEquals(Session[SessionKey.PPIDInfo.ToString()], null))
            {
                ///GET PPIDInfo FROM SESSION
                AcctListByICResponse = (retrieveAcctListByICResponse)Session[SessionKey.PPIDInfo.ToString()];

                ///LIST ONLY GSM A/C'S
                if (AcctListByICResponse.itemList.Where(c => c.Account != null && c.ServiceInfoResponse != null && ((c.ServiceInfoResponse.prinSuppInd != "" && c.ServiceInfoResponse.lob == "POSTGSM") || c.ServiceInfoResponse.lob == "HSDPA")).Count() > 0)
                {
                    SuppListAccounts = new SupplementaryListAccounts();

                    foreach (var v in AcctListByICResponse.itemList.Where(c => c.Account != null && c.ServiceInfoResponse != null && ((c.ServiceInfoResponse.prinSuppInd != "" && c.ServiceInfoResponse.lob == "POSTGSM") || c.ServiceInfoResponse.lob == "HSDPA")).ToList())
                    {
                        if (v.ServiceInfoResponse.prinSuppInd == "P" || v.ServiceInfoResponse.prinSuppInd == "")
                        {
                            SuppListAccounts.SuppListAccounts.Add(
                                new AddSuppInquiryAccount
                                {
                                    AccountNumber = v.AcctExtId,
                                    ActiveDate = v.Account.ActiveDate,
                                    Address = v.Account.Address,
                                    CompanyName = v.Account.CompanyName,
                                    Holder = v.Customer != null ? !string.IsNullOrEmpty(v.Customer.CustomerName) ? v.Customer.CustomerName : v.Account != null ? v.Account.Holder : string.Empty : v.Account != null ? v.Account.Holder : string.Empty,
                                    IDNumber = v.Account.IDNumber,
                                    IDType = v.Account.IDType,
                                    Plan = v.Account.Plan,
                                    SubscribeNo = v.Account.SubscribeNo,
                                    SubscribeNoResets = v.Account.SubscribeNoResets,
                                    AccountStatus = v.ServiceInfoResponse.serviceStatus,
                                    AccountName = v.ServiceInfoResponse.lob,
                                    AccountType = "P",
                                    externalId = v.ExternalId,
                                    accountExtId = v.AcctExtId,
                                    accountIntId = v.AcctIntId,
                                    IsMISM = v.IsMISM,
                                    Category = v.AccountDetails != null ? v.AccountDetails.AcctCategory.ToString2() : string.Empty,
                                    MarketCode = v.AccountDetails != null ? v.AccountDetails.MktCode.ToString2() : string.Empty,
                                    ParentID = v.AccountDetails != null ? v.AccountDetails.ParentId.ToString2() : string.Empty
                                });
                        }
                    }
                }
            }
            return View(SuppListAccounts);
        }

        [Authorize(Roles = "MREG_DSV,MREG_DSA,MREG_DSA,MREG_W,MREG_C,MREG_DSV,MREG_DSV,DREG_N,DREG_C,MREG_DAI,MREG_DAC,MREG_DC,MREG_DN")]
        public ActionResult SelectDevicePlan(int? type, string accid)
        {
			DropFourObj dropObj = new DropFourObj();
			Session[SessionKey.DedicatedSuppFlow.ToString()] = false;
            Session[SessionKey.Selected_Accessory.ToString()] = null;
            ViewBag.GSTMark = Settings.Default.GSTMark;
            List<String> LabelReplace = new List<String>();
            LabelReplace.Add("GSTMark");
            ViewBag.GSTnotif = WebHelper.GenerateLabelString(Settings.Default.GSTNotif, LabelReplace);
            Session["OrderType"] = (int)MobileRegType.NewLine;

			Session[SessionKey.MarketCode.ToString()] = null;
			Session[SessionKey.MSISDN.ToString()] = string.Empty;

            if (!string.IsNullOrEmpty(accid))
            {
                string[] AcntArray = accid.Split(',');
                //Session[SessionKey.KenanACNumber.ToString()] = AcntArray[2];

                Session[SessionKey.FxAccNo.ToString()] = AcntArray[0];
                Session[SessionKey.ExternalID.ToString()] = AcntArray[1];
                Session[SessionKey.AccExternalID.ToString()] = AcntArray[2];
                Session[SessionKey.KenanACNumber.ToString()] = AcntArray[3];
                Session[SessionKey.IsMISM.ToString()] = AcntArray[4];
                Session[SessionKey.AccountCategory.ToString()] = AcntArray[5];
                Session[SessionKey.MarketCode.ToString()] = AcntArray[6];
            }

            //var dropObj = (DropFourObj)Session[SessionKey.DropFourObj.ToString()];
            if (dropObj.currentFlow == DropFourConstant.MAIN_FLOW && dropObj.mainFlow.RegType == -1)
            {
                dropObj.mainFlow.RegType = (int)MobileRegType.DevicePlan;
            }
            else if (dropObj.currentFlow == DropFourConstant.SUPP_FLOW)
            {
                if (dropObj.suppFlow[dropObj.suppIndex - 1].RegType == -1)
                {
                    dropObj.suppFlow[dropObj.suppIndex - 1].RegType = (int)MobileRegType.DevicePlan;
                }
            }
            //else if (dropObj.currentFlow == DropFourConstant.MSISM_FLOW)
            //{
            //    if (dropObj.msimFlow[dropObj.msimIndex - 1].RegType == -1)
            //    {
            //        dropObj.msimFlow[dropObj.msimIndex - 1].RegType = (int)MobileRegType.DevicePlan;
            //    }
            //}
            Session[SessionKey.DropFourObj.ToString()] = dropObj;

            Session["_componentViewModel"] = null;
            Session[SessionKey.FromPromoOffer.ToString()] = null;
            
            Session[SessionKey.SelectedPlanID.ToString()] = null;
            Session[SessionKey.OfferId.ToString()] = null;

MobilityProd/Online.Registration.Web/Views/NewLine/BlacklistChecking.cshtml
@using Online.Registration.Web.Properties;
@using Online.Registration.Web.Helper;
@using SNT.Utility;
@model Online.Registration.Web.ViewModels.PersonalDetailsVM
@{
    ViewBag.Title = "Search Customer";
    var NewICCardTypeID = Util.GetIDByCode(RefType.IDCardType, Settings.Default.IDCardType_NRIC);
}

@using (Html.BeginForm("BlacklistChecking", "SuppLine", FormMethod.Post, new { id = "frmBlacklistChecking", @class = "overlayonsubmit", processmsg = "Loading" }))
{ 
    <div class="vwHeader">
        <table width="100%">
            <tr>
                <td>
                    <div>@ViewBag.Title</div>
                    <div class="vwSubHeader">Find Account</div>
                </td>
            </tr>
        </table>
    </div>
    <div class="viewInnerBody">
            @Html.ValidationSummary(false)
            <table>
                <tr>
                    <td><b>@Html.LabelFor(model => model.Customer.IDCardTypeID)</b></td>
                    <td>@(Html.Telerik().DropDownListFor(model => model.Customer.IDCardTypeID).BindTo(Util.GetList(RefType.IDCardType, defaultValue: "")))</td> 
                </tr>
                <tr>
                    <td><b>@Html.LabelFor(model => model.Customer.IDCardNo)</b></td>
                    <td>@Html.TextBoxFor(model => model.Customer.IDCardNo)</td>
                </tr>
                <tr>
                    <td>
                        <button value="Submit" type="button" onclick="submitNumpad()">Submit
                        </button>
                    </td>
                </tr>
            </table>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        var isNumpadTooltipOn;
        var tooltip = "Enter IC Number";

        $(document).ready(function () {

            $(".numbersonly").keypress(function (e) {
                return numbersonly(e, false);
            });

            var numpadInput = $("#numpadText");

            isNumpadTooltipOn = true;
            numpadInput.val(tooltip);
            numpadInput.addClass("tooltip");

            numpadInput.focus(function () {
                if (numpadInput.val() == tooltip) {
                    numpadInput.val("");
                    numpadInput.removeClass("tooltip");
                    isNumpadTooltipOn = false;
                }
            });

            numpadInput.focusout(function () {
                if (numpadInput.val() == "") {
                    numpadInput.val(tooltip);
                    numpadInput.addClass("tooltip");
                    isNumpadTooltipOn = true;
                }
            });

            $(".numpad button").click(function () {
                if (numpadInput.val() == "") {
                    numpadInput.val(tooltip);
                    numpadInput.addClass("tooltip");
                    isNumpadTooltipOn = true;
                }
                else if (isNumpadTooltipOn) {
                    numpadInput.val(numpadInput.val().replace(tooltip, ''));
                    numpadInput.removeClass("tooltip");
                    isNumpadTooltipOn = false;
                }

                if (numpadInput.val() == "") {
                    numpadInput.val(tooltip);
                    numpadInput.addClass("tooltip");
                    isNumpadTooltipOn = true;
                }
            });
            
            $(".button-continue").css("display", "none");

            
            $('#menuAddService').css("background-image", $('#menuAddService').css("background-image").replace(".png", "_hover.png"));
        });

        function submitNumpad(msisdn) {
            //var url = '@(Util.GetAbsoluteAppPath("/Registration/BlacklistChecking"))';
            var idCardNo = $('#Customer_IDCardNo').val();
            var idCardTypeID = $('#Customer_IDCardTypeID').val();

            var form = $("#frmBlacklistChecking");
            form.validate();

            if (form.valid()) {
                if(@(NewICCardTypeID) == idCardTypeID){
                
                    if($('#Customer_IDCardNo').val().length != 12){
                        alert('New IC must be 12 number.');
                        return false;
                    }
                }

                var url = '@(Url.Content("~/SuppLine/BlacklistChecking"))';
                $.post(url, { idCardNo: idCardNo, idCardTypeID: idCardTypeID }, function (data) {

                    window.location.href = '@(Url.Content("~/SuppLine/BlacklistResult?result="))' + data;

                });
            }
        }

    </script>
}

@section Styles{
    <style type="text/css">
        .divNumpad
        {
            position: relative;
            left: 50%;   
            top: 50%;
            margin-left: -20%;
            margin-top: 5%;
        }
        
    </style>
}

MobilityProd/Online.Registration.Web/Views/NewLine/BlacklistResult.cshtml
@using SNT.Utility;
@using Online.Registration.Web.Helper;
@using Online.Registration.Web.Controllers;
@{
    ViewBag.Title = "Customer Account";
    var isBlacklisted = ViewBag.isBlacklisted;
    var resultMsg = Session["RegMobileReg_ResultMessage"].ToString2();
    var accounts = (List<FoundAccounts>)ViewBag.Accounts;
}

@using (Html.BeginForm("BlacklistResult", "SuppLine", FormMethod.Post, new { id = "frmBlacklistResult", @class = "overlayonsubmit", processmsg = "Loading" }))
{ 
    <div class="vwHeader">
        <table width="100%">
            <tr>
                <td>
                    <div>@ViewBag.Title</div>
                    <div class="vwSubHeader">Found Account</div>
                </td>
            </tr>
        </table>
    </div>
    <div class="viewInnerBody">
            <table width="100%" style="text-align:center;">
                <tr>
                    <td>
                        @(Html.Telerik().Grid(accounts)
                                .Name("Grid").Selectable().DataKeys(a => a.Add("Name"))
                                .Columns(columns =>
                                {
                                    columns.Bound(o => o.Name);
                                    columns.Bound(o => o.ICNo);
                                    columns.Bound(o => o.MSISDN);
                                    columns.Bound(o => o.AccountNo);
                                })
                                .Footer(false)
) 
                    </td>
                </tr>
                <tr>
                    <td>
                        <p>&nbsp;</p>
                        @Html.Hidden("submit")
                        <button class="button-back2" type="submit" value="Back" onclick="$('#submit').val('back');">
                        </button>
                        
                        @*<button class="button-skip" type="submit" value="Skip" onclick="$('#submit').val('skip');">*@
                        <button class="button-continue2" type="submit" value="Next" onclick="$('#submit').val('next');">
                        </button>
                    </td>
                </tr>
            </table>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#menuAddService').css("background-image", $('#menuAddService').css("background-image").replace(".png", "_hover.png"));
        });
    </script>
}

MobilityProd/Online.Registration.Web/Views/NewLine/MobileRegAccCreated.cshtml
@using Online.Registration.Web.Helper;
@using System.Configuration;
@using SNT.Utility;
@{
    if (Roles.IsUserInRole("MREG_DAI") || Roles.IsUserInRole("MREG_DSV"))
    {
        ViewBag.Title = "Submit Registration";
    }
    else
    {
        ViewBag.Title = "Activate Service";
    }
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";

    int ReadyForPaymentStatusID = ConfigurationManager.AppSettings["ReadyForPaymentStatusID"].ToInt();
    int RegFailStatusID = ConfigurationManager.AppSettings["RegFailStatusID"].ToInt();

    bool isDealer = Session["IsDealer"].ToBool();
    var interval = ConfigurationManager.AppSettings["DealerTimerIntervel"].ToString();
}
@model int
@using (Html.BeginForm("MobileRegAccCreated", "NewLine", FormMethod.Post, new { id = "frmMobileRegAccCreated",  @class = "overlayonsubmit", processmsg = "Loading" }))
{           
<div class="success-header">
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
if (isDealer == true && (Roles.IsUserInRole("MREG_DSV") || Roles.IsUserInRole("MREG_DAI") || Roles.IsUserInRole("MREG_DIC")))
{
    @Html.Hidden("OrderId", Model.ToString2())
    <div id="dvDealer" class="success-body">
    <div id="divRegSubInProgress">
             <h4>
    @if(Roles.IsUserInRole("MREG_DAI") || Roles.IsUserInRole("MREG_DSV"))
    {
        @ConfigurationManager.AppSettings["DealerRegSubInProgress"].ToString() <img src= "@Url.Content("~/Content/img/shared/processing.gif")" alt="....." class="inprogressimg" />
    }
    else
    {
        @ConfigurationManager.AppSettings["DealerServiceRequestInProgress"].ToString() <img src= "@Url.Content("~/Content/img/shared/processing.gif")" alt="....." class="inprogressimg" />
    }
     </h4>
    </div>
    <div id="divRegSuccess" style="display:none;">
         <h4>
         @if (Roles.IsUserInRole("MREG_DAI") || Roles.IsUserInRole("MREG_DSV"))
         {
             @ConfigurationManager.AppSettings["DealerRegSubmitSuccess"].ToString()
         }
         else
         {
             @ConfigurationManager.AppSettings["DealerServiceRequestSuccess"].ToString()
         }
             </h4>
        <h4>
             Click
        @Html.ActionLink("HERE", "MobileRegSummary", new { regID = Html.DisplayForModel() }, new { style = "color:#5fb848;font-weight:bold;text-decoration:none" })
        to view registration or <a href="@(Url.Content("~/Registration/PrintContractDetails?id=" + Model))" target="_blank" style="text-decoration:none" >
            <img  alt="Print" src='@Url.Content("~/Content/images/Print.gif")' />
            Print </a>the registration form.
        </h4>
    </div>
    <div id="divRegFail" class="success-body" style="display:none; text-align:center;">
        <h4 style="color:Red">
        @if (Roles.IsUserInRole("MREG_DAI") || Roles.IsUserInRole("MREG_DSV"))
        {
            @ConfigurationManager.AppSettings["DealerRegUnSuccess"].ToString()
        }
        else
        {
            @ConfigurationManager.AppSettings["DealerServiceRequestFail"].ToString()
        }
         </h4>
    </div>
    
    @*<div id="divLoading" style="text-align: center;">
        <img id="imgloading" src="../../Content/img/shared/loading.gif" width="50" height="50" /></div>*@
    <div style="text-align: right; padding: 20px;">
     @if (User.IsInRole("MREG_DAC") || User.IsInRole("MREG_DIC") || User.IsInRole("MREG_DSV") || User.IsInRole("MREG_DCH"))
     {
        <input id="btnReadyforpayment" type="button" class="submitButton" value="Back To Inventory" onclick="redirectToPage('@(string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~/Registration/StoreKeeper")))')" />}
    </div>
    </div>
}
else
{
<div class="success-body">
    <h3>
       New service request has been sent successfully.</h3>
    <h4>
        Click
        @Html.ActionLink("HERE", "MobileRegSummary", new { regID = Html.DisplayForModel() }, new { style = "color:#5fb848;font-weight:bold;text-decoration:none" })
        to view registration or <a href="@(Url.Content("~/Registration/PrintContractDetails?id=" + Model))" target="_blank" style="text-decoration:none" >
            <img  alt="Print" src='@Url.Content("~/Content/images/Print.gif")' />
            Print </a>the registration form.
    </h4>
</div>
}
}
@section Scripts{
    <script type="text/javascript" language="javascript">
        if ('@(isDealer)' == "True") {
            $(document).ready(function () {

                $("#divRegSuccess").hide();
                $("#divRegFail").hide();

                ajaxcall();

            });

            var url = '@(Url.Content("~/NewLine/GetRegStatus"))';

            function ajaxcall() {
                $.ajax({
                    url: url,
                    data: { 'regId': '@Model' },
                    type: 'GET',
                    dataType: 'json',
                    success: function (result) {
                        if (result != '@ReadyForPaymentStatusID' && result != '@RegFailStatusID') {
                            
                            if (result == -500) {
                                window.location.href = '@(Url.Content("~/NewLine/MobileRegSvcActivated/"))' + '@Model';
                            }

                            setTimeout(ajaxcall, '@interval');
                        }
                        else if (result == '@RegFailStatusID') {
                            $("#divRegSubInProgress").hide();
                            $('#btnReadyforpayment').hide();
                            $("#divRegFail").show();
                        }
                        else {
                            $("#divRegSubInProgress").hide();
                            $("#divRegSuccess").show();
//                            $("#btnReadyforpayment").removeAttr("disabled");
//                            $('#btnReadyforpayment').removeClass('disabled');
//                            $('#btnReadyforpayment').addClass('submitButton');
                        }
                    }
                });
            }

            $("#btnReadyforpayment").click(function () {
                //alert("submit");
            });
        }
    </script>
}

MobilityProd/Online.Registration.Web/Views/NewLine/MobileRegClosed.cshtml
@using Online.Registration.Web.Helper;
@{
    ViewBag.Title = "Close Registration";
    Layout = "~/Views/Shared/_SubmitLayout.cshtml";
}
@model int
<div>
    <table width="100%">
        <tr>
            <td style="width: 580px">
                <div>@ViewBag.Title</div>
            </td>
        </tr>
    </table>
</div>
<div>
    <h3>
        Registration has been closed Successfully.</h3>
</div>

MobilityProd/Online.Registration.Web/Views/NewLine/MobileRegSuccess.cshtml
@using Online.Registration.Web.Helper;
@using SNT.Utility;
@using Online.Registration.Web.Properties;
@{
    ViewBag.Title = "MobileRegSuccessNew";
    Layout = "~/Views/Shared/_NewLayout.cshtml";

    var emailAddress = (string)Session[Online.Registration.Web.CommonEnum.SessionKey.Email.ToString()];
    var queueNo = (string) Session[Online.Registration.Web.CommonEnum.SessionKey.QueueNo.ToString()];
    var customerFullName = (string)Session[Online.Registration.Web.CommonEnum.SessionKey.FullName.ToString()];
    

    var viewOrderURL = Url.Action("MobileRegSummary", "Registration", new { regID = Html.DisplayForModel() });
    var printOrderURL = Url.Action("PrintContractDetails", "Registration") + "?id=" + Html.DisplayForModel();
    var homeURL = Url.Action("IndexNew", "Home");
    
}
<div class="container" id="new-cus">
    <div class="isell-base-2">
        <div class="row">
            <div class="col-sm-12">
                <h2>
                    New registration:
                </h2>
                <h4>
                    @customerFullName</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 green-bg">
                <p class="font-24">
                    Add a Plan & Device</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 success">
                <h1>Your Order has been submitted.</h1>
                @if (!string.IsNullOrEmpty(emailAddress) && !Roles.IsUserInRole("MREG_CUSR"))
                {
                    <p>We will send a confirmation email upon payment received to <span>@emailAddress</span></p>
                }
                else
                {
                    <p>Registration has been submitted successfully.</p>
                }
                @if (!string.IsNullOrEmpty(queueNo))
                {
                    <p class="bold-16">
                        Your queue number is:</p>
                    <p class="num-q">
                        @queueNo</p>
                }
            </div>
            <ul class="col-sm-11 home">
                <li id="viewOrder" class="col-sm-4">
                    <div class="option-box">
                        <div class="view-order">
                        </div>
                        <h2>
                            View Order</h2>
                    </div>
                </li>
                <li id="printOrder" class="col-sm-4">
                    <div class="option-box">
                        <div class="print">
                        </div>
                        <h2>
                            Print Order</h2>
                    </div>
                </li>
                <li id="home" class="col-sm-4">
                    <div class="option-box">
                        <div class="back-home">
                        </div>
                        <h2>
                            Home</h2>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#viewOrder').click(function (e) {
            e.preventDefault();
            window.location.href = '@viewOrderURL';
        });
        $('#printOrder').click(function (e) {
            e.preventDefault();
            var win = window.open('@printOrderURL', '_blank');
            win.focus();
        });
        $('#home').click(function (e) {
            e.preventDefault();
            window.location.href = '@homeURL';
        });
    });
</script>

MobilityProd/Online.Registration.Web/Views/NewLine/_Billing.cshtml
@using Online.Registration.Web.Helper;
@{
    ViewBag.Title = "_Billing";
}

@model Online.Registration.Web.ViewModels.PersonalDetailsVM
               
<table width="500px">
    <tr>
        <td><b>@Html.LabelFor(model => model.Customer.PayModeID)</b></td>
        @*<td>@(Html.Telerik().DropDownListFor(model => model.Customer.PayModeID).BindTo(Util.GetList(RefType.PaymentMode, defaultValue: "")).ClientEvents(events => events.OnChange("paymodeChanged")))</td> *@
        <td>@(Html.Telerik().DropDownListFor(model => model.Customer.PayModeID).BindTo(Util.GetList(RefType.PaymentMode, defaultValue: "0", selectedValue: "1")).ClientEvents(events => events.OnChange("paymodeChanged")))</td> 
    </tr>
    @*<tr>
        <td><div class="autoBilling"><b>@Html.LabelFor(model => model.Customer.CardTypeID)</b></div></td>
        <td><div class="autoBilling">@(Html.Telerik().DropDownListFor(model => model.Customer.CardTypeID).BindTo(Util.GetList(RefType.CardType, defaultValue: "")))</div></td> 
    </tr>
    <tr>
        <td><div class="autoBilling"><b>@Html.LabelFor(model => model.Customer.CardNo)</b></div></td>
        <td><div class="autoBilling">@Html.TextBoxFor(model => model.Customer.CardNo)&nbsp;&nbsp;eg.4234990256302271 </div></td>
    </tr>
    <tr>
        <td><div class="autoBilling"><b>@Html.LabelFor(model => model.Customer.CardExpiryDate)</b></div></td>
        <td><div class="autoBilling">@Html.TextBoxFor(model => model.Customer.CardExpiryDate)&nbsp;&nbsp;eg. MMYY</div></td>
    </tr>
    <tr>
        <td><div class="autoBilling"><b>@Html.LabelFor(model => model.Customer.NameOnCard)</b></div></td>
        <td><div class="autoBilling">@Html.TextBoxFor(model => model.Customer.NameOnCard, new { @class = "uppercase", onchange = "toUpperCase(this)" })</div></td>
    </tr>*@
</table>